### ISSUE TITLE
Inconsistent vars handling within set_fact block (hashtag82698)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/ansible_jan01#18]
hashtaghashtaghashtag Summary

Using `vars` alongside `set_fact` has inconsistent behaviour when an existing variable is overwritten in the vars block.

hashtaghashtaghashtag Issue Type

Bug Report

hashtaghashtaghashtag Component Name

set_fact

hashtaghashtaghashtag Ansible Version

```console
$ ansible --version
ansible [core 2.16.3]
  config file = /repo/ansible.cfg
  configured module search path = ['/home/dm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dm/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /repo/collections
  executable location = /home/dm/.local/bin/ansible
  python version = 3.12.1 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

hashtaghashtaghashtag Configuration

```console
hashtag if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
COLLECTIONS_PATHS(/repo/ansible.cfg) = ['/repo/collections']
CONFIG_FILE() = /repo/ansible.cfg
DEFAULT_PRIVATE_KEY_FILE(/repo/ansible.cfg) = /repo/id_ansible_rsa
DEFAULT_REMOTE_USER(/repo/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/repo/ansible.cfg) = ['/repo/roles']
EDITOR(env: EDITOR) = /usr/bin/vim
HOST_KEY_CHECKING(/repo/ansible.cfg) = False
VARIABLE_PLUGINS_ENABLED(/repo/ansible.cfg) = ['host_group_vars', 'community.sops.sops'] 

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/repo/ansible.cfg) = False
private_key_file(/repo/ansible.cfg) = id_ansible_rsa
remote_user(/repo/ansible.cfg) = ansible

ssh:
___
host_key_checking(/repo/ansible.cfg) = False
private_key_file(/repo/ansible.cfg) = id_ansible_rsa
remote_user(/repo/ansible.cfg) = ansible
```

hashtaghashtaghashtag OS / Environment

Ubuntu 22.04 guest, and Fedora 39 host.

hashtaghashtaghashtag Steps to Reproduce

```yaml (paste below)
- ansible.builtin.set_fact:
    status: "no a json"

- ansible.builtin.shell: >
     echo "{ \"Self\": { \"Online\": true }, \"Version\": 1.0 }"
  changed_when: false
  register: tailscale_status

- vars:
    status: "{{ tailscale_status.stdout | from_json }}" hashtag <- does not take place
  ansible.builtin.set_fact:
    tailscale_is_online: "{{ status.Self.Online }}"
    tailscale_version: "{{ status.Version }}"
```

hashtaghashtaghashtag Expected Results

Consistency. Either `status` is updated all the time, or never within the set_fact block.

hashtaghashtaghashtag Actual Results

```console
If `status` is not already defined beforehand the instruction pointed at is executed, and value usable in followup set_fact. If `status` is already defined, the current `status` value is used within the set_fact.
```

hashtaghashtaghashtag Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
)
