### ISSUE TITLE
[dnf] Installing package does not respect wildcard character in local filename (hashtag82689)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/ansible_jan01#20]
hashtaghashtaghashtag Summary

I have a custom file `/tmp/build/beanstalkd-git-1.13_x86_64.rpm`:

The following task fails when trying to use a wildcard in the name:

```
- name: 'Install beanstalkd package'
  ansible.builtin.dnf:
    name: "/tmp/build/beanstalkd-git-*.rpm"
    state: present
```

Output:
```
Could not open: /tmp/build/beanstalkd/beanstalkd-git-*.rpm\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

Manually installing with `dnf install /tmp/build/beanstalkd/beanstalkd-git-*.rpm` works fine and finds the file using the wildcard.

I see wildcard support for dnf remove command in  but not sure if it also works for install.

hashtaghashtaghashtag Issue Type

Bug Report

hashtaghashtaghashtag Component Name

dnf

hashtaghashtaghashtag Ansible Version

```console
$ ansible --version
ansible [core 2.16.2]
```

hashtaghashtaghashtag Configuration

```console
hashtag if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

hashtaghashtaghashtag OS / Environment

Fedora 39

hashtaghashtaghashtag Steps to Reproduce

```yaml (paste below)
- name: 'Install beanstalkd package'
  ansible.builtin.dnf:
    name: "/tmp/build/beanstalkd-git-*.rpm"
    state: present
```

hashtaghashtaghashtag Expected Results

To respect the wildcard for filenames. 

hashtaghashtaghashtag Actual Results

```console
Could not open: /tmp/build/beanstalkd/beanstalkd-git-*.rpm\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

hashtaghashtaghashtag Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
)
